//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1026
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public static class TimeHelper {

		public const int MILLIES_PER_DAY = 86400000;

		public static float TimeOfDayInMillies(DateTime dateTime) {

			return TimeToMillies (dateTime.Hour, dateTime.Minute, dateTime.Second, dateTime.Millisecond);
		}
		
		public static float TimeToMillies (int hours) {
			
			return hours * 60 * 60 * 1000;
		}
		
		public static float TimeToMillies (int hours, int minutes) {

			return minutes * 60 * 1000 + TimeToMillies(hours);
		}

		public static float TimeToMillies(int hours, int minutes, int seconds) {

			return seconds * 1000 + TimeToMillies (hours, minutes);
		}

		public static float TimeToMillies(int hours, int minutes, int seconds, int millies) {

			return millies + TimeToMillies (hours, minutes, seconds);
		}
	}
}

